# Flow应用配置
app:
  name: "flow"
  version: "1.0.0"
  mode: "debug"
  log_level: "info"

# 数据库配置
database:
  default: "master"
  connections:
    master:
      driver: "mysql"
      host: "localhost"
      port: 3306
      database: "flow_db"
      username: "root"
      password: "password"
      charset: "utf8mb4"
      max_idle_conns: 10
      max_open_conns: 100
      
    slave:
      driver: "mysql"
      host: "localhost"
      port: 3307
      database: "flow_db"
      username: "readonly"
      password: "readonly"
      charset: "utf8mb4"
      max_idle_conns: 5
      max_open_conns: 50

    postgres:
      driver: "postgres"
      host: "localhost"
      port: 5432
      database: "flow_reports"
      username: "postgres"
      password: "postgres"
      sslmode: "disable"
      
    sqlite:
      driver: "sqlite3"
      database: ":memory:"